### ISSUE TITLE
Certificate Password

### ISSUE THREAD

**Issue by sysvar** [EtiennePerot/easy-openvpn#1]
This script is fantastic, appriciate the hard work! 

This script is fine as it is for everyone else but...
I would like to add a certificate password as well, so that there is a prompt for clients to have to type in their own set password on the server, This is so that when connecting to the VPN they have to unlock their certificate in order to connect to the server. Can you point me in the right direction?

Thanks.

**Comment by EtiennePerot** [comment]
Hmm, you self-closed this issue it seems. Did you figure it out?

That being said, I'd rather not include functionality to customize this in the script, as the purpose of the script is to be opinionated and allow only as much customization as is strictly necessary. Adding passwords to certificates is a pretty obscure customization in my opinion.

**Comment by sysvar** [comment]
Yes don't worry, I used something else instead.
